logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

spring.profiles.active=@spring.profiles.active@

server.port=8082

logging.level.com.payment=debug

#spring.profiles.active=dev








